# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

mysql:
    type: mariadb:10.2
    disk: 1024

redis:
    type: redis:3.0

solr:
    type: solr:4.10
    disk: 1024